[DOCS] Update custom objective function docs
microsoft/LightGBM pull request #3502
Opened 2020-10-29 20:03 UTC by hsorsky

Hopefully this serves to provide better documentation for using custom objective functions. 

AFAIK the logic stated here is correct, but please let me know if not - I was the one who opened this issue originally because I didn't understand the inputs, so I may still not.

Closes #3149. 

**TODO:**
- [ ] I'd also like to add an example of using a custom objective function (or even just an example of the regular objective function, but manually implemented) as part of this PR, but I don't know where is best to add it. Any suggestions?

2020-10-31 02:55 UTC, btrotta commented
@hsorsky Thanks, this is a really useful improvement!

Re your todo, we already have an example here: https://github.com/microsoft/LightGBM/blob/e83042f20633d7f74dda0d18624721447a610c8b/examples/python-guide/advanced_example.py#L136 
But I think it would be good to add a link to this in the docs

2021-01-03 15:33 UTC, jameslamb requested changes
@hsorsky thanks for your contribution! Could you please update this branch to the latest `master`? I left one suggestion as well about where to put a link to the custom-objective example, based on @btrotta 's comment.

2021-01-03 15:33 UTC, jameslamb commented on python-package/lightgbm/sklearn.py
> +        ``y_pred[j * num_data + i]``, and you should group ``grad`` and ``hess`` in this way as well.
```suggestion
        ``y_pred[j * num_data + i]``, and you should group ``grad`` and ``hess`` in this way as well.
        
        For an example using a custom objective function, please see
        https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/advanced_example.py
```

2021-03-26 13:31 UTC, StrikerRUS commented
Please feel free to reopen if still interested in this contribution.

2021-03-26 13:31 UTC, closed without merging