Update MacOS version
microsoft/LightGBM pull request #3505
Opened 2020-10-29 20:32 UTC by nabokovas

There is a new version of The macOS Build Environment. So I propose changes for you to use a modern one. https://docs.travis-ci.com/user/reference/osx/

2020-10-29 20:49 UTC, jameslamb requested changes
Thanks for taking the time to contribute! But I'm -1 on this change.

We do try to test LightGBM against somewhat-reason versions of software, but we also want to be sure that the library works well on widely-used configurations.  XCode 12.2 is less than a month old (https://xcodereleases.com/), so I'd guess that many of our users who are using LightGBM on Mac haven't updated to it.

But I'll defer to @StrikerRUS 's opinion

2020-10-29 22:42 UTC, StrikerRUS approved these changes
@nabokovas Thank you very much for this update! You've just done my job 🙂 

@jameslamb Let me kindly disagree with you. According to our policy, we try to use the most recent environments at Travis (https://github.com/microsoft/LightGBM/pull/3393#issue-486186591) and update them quite often.

![image](https://user-images.githubusercontent.com/25141164/97639748-3d1dc880-1a50-11eb-8fd4-ec207de3df4c.png)


I believe it's better to spot a compilation problem at our CI before users come and report it.
Moreover, we are speaking about macOS where it seems users tend to use the last available software in contrast to Linux where one have to use 10-years old CentOS distribution.

FYI, yesterday I tried to use Big Sur, but unfortunately without any luck due to dependency unavailability: #3499.

2020-10-30 00:04 UTC, jameslamb commented
ah I see, ok then I am ok with this change.

2020-10-30 00:04 UTC, jameslamb approved these changes

2020-10-30 14:11 UTC, merged