added f-strings to python-package/setup.py
microsoft/LightGBM pull request #4145
Opened 2021-03-30 16:29 UTC by NovusEdge

2021-03-30 20:11 UTC, StrikerRUS requested changes
One mistake below, everything else looks fine!

2021-03-30 20:11 UTC, StrikerRUS commented on python-package/setup.py
> +                    logger.info(f"Starting to compile with %s (%s).", vs, arch)
```suggestion
                    logger.info(f"Starting to compile with {vs} ({arch}).")
```

2021-03-31 01:24 UTC, NovusEdge commented
> One mistake below, everything else looks fine!

Could you please mention the line where the mistake is.

2021-03-31 02:31 UTC, jameslamb commented
> > One mistake below, everything else looks fine!
> 
> Could you please mention the line where the mistake is.

it is right here: https://github.com/microsoft/LightGBM/pull/4145#discussion_r604399154

2021-03-31 11:34 UTC, StrikerRUS commented
@NovusEdge 
> Could you please mention the line where the mistake is.

GitHub review comments are posted with a small visible piece of code. Most often, the last line of that codepiece is the line review comment is referring to.

![image](https://user-images.githubusercontent.com/25141164/113137643-78096f80-922d-11eb-98fe-b544ef486cd5.png)


Also, GitHub has recently introduced "Review suggestions". So that reviewers now can suggest code changes directly in the review comments:

![image](https://user-images.githubusercontent.com/25141164/113137835-b868ed80-922d-11eb-9332-0cb0d4846995.png)

Contributors, in case they are agree with a suggestion, are able to commit the suggested change directly in the browser by clicking "Commit suggestion" button or commit multiple suggestion at one time ("Add suggestion to batch" button).

2021-03-31 11:35 UTC, StrikerRUS approved these changes
@NovusEdge Thanks for your contribution!

2021-03-31 11:36 UTC, merged