[python-package] allow custom weighing in fobj for scikit-learn API
microsoft/LightGBM pull request #5211
Opened 2022-05-13 23:43 UTC by jmoralez

This removes the automatic weighing for `grad` and `hess` when using a custom objective in the scikit-learn API and makes the signature equivalent to the custom eval `(y_true, y_pred, weight, group)`.

Also adds tests to check that the behavior using the built-in objectives and the custom ones is consistent, i.e. if we give the weights to the dataset/fit using the built-in objectives we get the same results as if we use custom objectives and do the weighing ourselves. 

Closes #5027.

2022-05-14 21:36 UTC, StrikerRUS requested changes
Thank you so much for picking up this issue!
Please consider checking some my minor comments below:

2022-05-14 21:36 UTC, StrikerRUS commented on tests/python_package_test/test_sklearn.py
> +        weight_valid = None
I think this is a little bit more readable by avoiding code duplication.
```suggestion
    train_test_split_func = partial(train_test_split, test_size=0.2, random_state=0)
    X_train, X_valid, y_train, y_valid = train_test_split_func(X, y)
    if use_weight:
        weight = np.full_like(y, 2)
        weight_train, weight_valid = train_test_split_func(weight)
    else:
        weight_train = None
        weight_valid = None
```

2022-05-14 21:36 UTC, StrikerRUS commented on tests/python_package_test/test_sklearn.py
> +    )
We have a built-in `eval_result` in sklearn estimators.
https://github.com/microsoft/LightGBM/blob/2871b53e8e5e0ef23590410d7596d91173322ae4/python-package/lightgbm/sklearn.py#L749-L750
```suggestion
    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train,
        y_train,
        sample_weight=weight_train,
        eval_set=[(X_train, y_train), (X_valid, y_valid)],
        eval_names=['train', 'valid'],
        eval_sample_weight=[weight_train, weight_valid],
        eval_metric=custom_eval,
    )
    eval_result = model.evals_result_
```

2022-05-16 18:47 UTC, jmoralez commented on python-package/lightgbm/sklearn.py
> +            or ``func(y_true, y_pred, weight, group)``
Addressed in 71b3ba4

2022-05-23 22:04 UTC, StrikerRUS commented
@shiyu1994 Would you like to take a look at this PR as you were a creator of #5027?

2022-06-04 22:43 UTC, StrikerRUS commented
@shiyu1994

2022-06-12 15:51 UTC, StrikerRUS commented
@shiyu1994

2022-06-25 17:33 UTC, StrikerRUS commented
@jameslamb Please help with a second review.

2022-06-27 02:29 UTC, jameslamb approved these changes
Thanks for this! I believe I understand the changes, prior discussion on this PR, and previous discussion in #5207.

It's unfortunate that we have to make the breaking change where providing a callable that takes 3 arguments will now be treated as `(y_true, y_pred, weight)` when previous releases treated it as `(y_true, y_pred, group)`, since the values in `weight` and `group` can be similar and therefore code that worked in `lightgbm` v3.3.2 could **silently** start producing incorrect results in v4.0.0.

But I agree that that's worth it in exchange for consistency with the existing interface for scikit-learn **eval** functions, as @StrikerRUS mentioned in 

https://github.com/microsoft/LightGBM/issues/5027#issuecomment-1049283105

Since v4.0.0 will contain many breaking changes intended to reduce inconsistencies, and since the project's current state doesn't really support doing a round of deprecation warnings first (e.g. https://github.com/microsoft/LightGBM/pull/5133#pullrequestreview-995964570).

2022-06-27 23:29 UTC, merged