[R-package] Fix error when passing categorical features to lightgbm()
microsoft/LightGBM pull request #6003
Opened 2023-07-22 18:56 UTC by david-cortes

fixes #6000 

This PR fixes an error when supplying dataset parameters to `lightgbm()`, such as `categorical_feature`. Before this PR, the dataset was constructed with `free_raw_data=TRUE`, which impeded it from using parameters that require the raw data after dataset creation.

2023-07-24 03:35 UTC, jameslamb requested changes
Thanks for identifying this issue and taking the time to submit a PR! But I think we should pursue a different fix... setting `free_raw_data=FALSE` this way means unnecessarily storing a copy of the passed-in `data` throughout training, which might cause out-of-memory issues for users.

Did you explore simply moving this call

https://github.com/microsoft/LightGBM/blob/44928d3ae3f3ece7cbf577d59e892333f60508ee/R-package/R/lgb.train.R#L182-L185

up further in `lgb.train()`, so it's run prior to the Dataset being constructed here?

https://github.com/microsoft/LightGBM/blob/44928d3ae3f3ece7cbf577d59e892333f60508ee/R-package/R/lgb.train.R#L157

I haven't tested that yet, but I *think* it should solve the issue without requiring changes to `lightgbm()` or holding an extra copy of the training data in memory. Could you please try that?

2023-07-24 03:36 UTC, jameslamb commented
Also don't worry about the CUDA CI job failures... we have a repo-wide issue with those jobs right now: #6001

Sorry for the inconvenience.

2023-07-24 17:44 UTC, david-cortes commented
> Thanks for identifying this issue and taking the time to submit a PR! But I think we should pursue a different fix... setting `free_raw_data=FALSE` this way means unnecessarily storing a copy of the passed-in `data` throughout training, which might cause out-of-memory issues for users.
> 
> Did you explore simply moving this call
> 
> https://github.com/microsoft/LightGBM/blob/44928d3ae3f3ece7cbf577d59e892333f60508ee/R-package/R/lgb.train.R#L182-L185
> 
> up further in `lgb.train()`, so it's run prior to the Dataset being constructed here?
> 
> https://github.com/microsoft/LightGBM/blob/44928d3ae3f3ece7cbf577d59e892333f60508ee/R-package/R/lgb.train.R#L157
> 
> I haven't tested that yet, but I _think_ it should solve the issue without requiring changes to `lightgbm()` or holding an extra copy of the training data in memory. Could you please try that?

Yes, that also seems to fix the issue.

2023-08-04 15:40 UTC, jameslamb approved these changes
Confirmed that this test produces the error from #6000 on latest `master`, and that it's resolved here.

Thanks for the help as always!

2023-08-04 15:40 UTC, merged